ProfessionFramework.addTrait('CameronOP1', {
    name = "CameronOP1",
    description = "Cameron said he would join us if i could make him a GOD.",
    icon = "trait_Cameron",
    cost =  1,
    xp = {
		    [Perks.Strength] = 10,
		    [Perks.Fitness] = 10,
	    	[Perks.Agility] = 10,
            [Perks.Sprinting] = 10,
		    [Perks.Lightfoot] = 10,
	    	[Perks.Nimble] = 10,
            [Perks.Sneak] = 10,
		    [Perks.Axe] = 10,
		    [Perks.Tailoring] = 10,
	    	[Perks.Cooking] = 10,
            [Perks.Farming] = 10,
		    [Perks.Doctor] = 10,
	    	[Perks.Electricity] = 10,
            [Perks.MetalWelding] = 10,
	    	[Perks.Fishing] = 10,
            [Perks.PlantScavenging] = 10,
		    [Perks.Trapping] = 10,
    },
})

ProfessionFramework.addTrait('CameronOP2', {
    name = "CameronOP2",
    description = "Cameron said he would join us if i could make him a GOD.",
    icon = "trait_Cameron",
    cost =  1,
    xp = {
	    	[Perks.Blunt] = 10,
            [Perks.SmallBlunt] = 10,
            [Perks.Mechanics] = 10,
		    [Perks.LongBlade] = 10,
	    	[Perks.SmallBlade] = 10,
            [Perks.Spear] = 10,
		    [Perks.Maintenance] = 10,
	    	[Perks.Aiming] = 10,
            [Perks.Reloading] = 10,
		    [Perks.Woodwork] = 10,
    },
})